### ISSUE TITLE
Can't make prettier to work as an ESLint rule

### ISSUE THREAD

**Issue by eugenet8k** [helixbass/eslint-plugin-coffee#34]
Hi, thank you so much for the great work! We are trying to adopt the new plugin for our big codebase which is a mix of Coffee and JS modules. We used `overrides` in the `.eslintrc` to add rules and parser for coffee files:

```
{
  "parser": "babel-eslint",
  "extends": [
    "airbnb",
    "prettier",
    "prettier/react",
    "plugin:prettier/recommended",
    "plugin:mocha/recommended"
  ],
  "plugins": ["prettier", "react-hooks", "emotion", "mocha"],
  "overrides": [
    {
      "files": ["**/*.coffee"],
      "parser": "eslint-plugin-coffee",
      "plugins": ["coffee"],
      "extends": [
        "plugin:coffee/airbnb",
        "plugin:coffee/import"
      ]
    }
  ]
}
```

and we have all the recent versions in packages.json:
```
    "eslint": "6.8.0",
    "eslint-config-airbnb": "18.0.1",
    "eslint-config-prettier": "6.9.0",
    "eslint-plugin-coffee": "0.1.12",
    "eslint-plugin-emotion": "10.0.27",
    "eslint-plugin-import": "2.20.0",
    "eslint-plugin-jsx-a11y": "6.2.3",
    "eslint-plugin-mocha": "6.2.2",
    "eslint-plugin-prettier": "3.1.2",
    "eslint-plugin-react": "7.18.0",
    "eslint-plugin-react-hooks": "2.3.0",
    "prettier": "1.19.1",
    "prettier-eslint": "9.0.1",
    "prettier-eslint-cli": "5.0.0",
```

When we follow manual from https://github.com/helixbass/eslint-plugin-coffee#usage-with-prettier, and add `"extends": ["plugin:coffee/prettier-run-as-rule"]` into our config as:

```
{
  "parser": "babel-eslint",
  "extends": [
    "airbnb",
    "prettier",
    "prettier/react",
    "plugin:prettier/recommended",
    "plugin:mocha/recommended"
  ],
  "plugins": ["prettier", "react-hooks", "emotion", "mocha"],
  "overrides": [
    {
      "files": ["**/*.coffee"],
      "parser": "eslint-plugin-coffee",
      "plugins": ["coffee"],
      "extends": [
        "plugin:coffee/airbnb",
        "plugin:coffee/import",
        "plugin:coffee/prettier-run-as-rule"
      ]
    }
  ]
}
```

Both VSCode and command line eslint checks fail with :

```
Error: Couldn't resolve parser "coffeescript"
Occurred while linting app/app/controllers/base/controller.coffee:1
    at resolveParser (app/node_modules/prettier/index.js:9710:15)
    at normalize$1 (app/node_modules/prettier/index.js:9803:16)
    at formatWithCursor (app/node_modules/prettier/index.js:13525:12)
    at app/node_modules/prettier/index.js:44207:15
    at Object.format (app/node_modules/prettier/index.js:44226:12)
    at Program (app/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:240:41)
    at app/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>:null:null)
    at Object.emit (app/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (app/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (app/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (app/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (app/node_modules/eslint-plugin-coffee/lib/code-path-analysis/code-path-analyzer.js:577:21)
    at app/node_modules/eslint/lib/linter/linter.js:936:32
    at Array.forEach (<anonymous>:null:null)
    at runRules (app/node_modules/eslint/lib/linter/linter.js:931:15)
    at Linter._verifyWithoutProcessors (app/node_modules/eslint/lib/linter/linter.js:1157:31)
    at Linter._verifyWithConfigArray (app/node_modules/eslint/lib/linter/linter.js:1255:21)
    at Linter.verify (app/node_modules/eslint/lib/linter/linter.js:1210:25)
    at Linter.verifyAndFix (app/node_modules/eslint/lib/linter/linter.js:1400:29)
    at verifyText (app/node_modules/eslint/lib/cli-engine/cli-engine.js:230:48)
    at CLIEngine.executeOnFiles (app/node_modules/eslint/lib/cli-engine/cli-engine.js:798:28)
    at Object.execute (app/node_modules/eslint/lib/cli.js:212:111)
    at Object.<anonymous> (app/node_modules/eslint/bin/eslint.js:107:28)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

**Comment by eugenet8k** [comment]
Shortly after I found the installation manual of a forked `prettier` that supports CoffeeScript here https://github.com/helixbass/prettier-plugin-coffeescript#install. I got it working now! Leaving this ticket as a potential help to others. Maybe it worth updating Readme explicitly stating that a forked `prettier` is required.
