### ISSUE TITLE
Error if React Component has undefined or class member property spread

### ISSUE THREAD

**Issue by eugenet8k** [helixbass/eslint-plugin-coffee#35]
Hi, we have cases where React Components are instantiated using the properties stores as a class instance property. This crashes the plugin. The code example:

```
import React from 'react'

export default class ReactView
  props: label: 'test'

  render: ->
    <div>
      <span {@props...}>test</span>
    </div>
```

the ESLint check crashes with:

```
TypeError: Cannot read property 'defs' of undefined
Occurred while linting project/react-error.coffee:8
    at project/node_modules/eslint-plugin-coffee/lib/rules/no-danger-with-children.js:79:34
    at Array.find (<anonymous>:null:null)
    at findJsxProp (project/node_modules/eslint-plugin-coffee/lib/rules/no-danger-with-children.js:75:27)
    at JSXElement (project/node_modules/eslint-plugin-coffee/lib/rules/no-danger-with-children.js:106:64)
    at project/node_modules/eslint/lib/linter/safe-emitter.js:45:58
    at Array.forEach (<anonymous>:null:null)
    at Object.emit (project/node_modules/eslint/lib/linter/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (project/node_modules/eslint/lib/linter/node-event-generator.js:254:26)
    at NodeEventGenerator.applySelectors (project/node_modules/eslint/lib/linter/node-event-generator.js:283:22)
    at NodeEventGenerator.enterNode (project/node_modules/eslint/lib/linter/node-event-generator.js:297:14)
    at CodePathAnalyzer.enterNode (project/node_modules/eslint-plugin-coffee/lib/code-path-analysis/code-path-analyzer.js:577:21)
    at project/node_modules/eslint/lib/linter/linter.js:936:32
    at Array.forEach (<anonymous>:null:null)
    at runRules (project/node_modules/eslint/lib/linter/linter.js:931:15)
    at Linter._verifyWithoutProcessors (project/node_modules/eslint/lib/linter/linter.js:1157:31)
    at Linter._verifyWithConfigArray (project/node_modules/eslint/lib/linter/linter.js:1255:21)
    at Linter.verify (project/node_modules/eslint/lib/linter/linter.js:1210:25)
    at Linter.verifyAndFix (project/node_modules/eslint/lib/linter/linter.js:1400:29)
    at verifyText (project/node_modules/eslint/lib/cli-engine/cli-engine.js:230:48)
    at CLIEngine.executeOnFiles (project/node_modules/eslint/lib/cli-engine/cli-engine.js:798:28)
    at Object.execute (project/node_modules/eslint/lib/cli.js:212:111)
    at Object.<anonymous> (project/node_modules/eslint/bin/eslint.js:107:28)
    at Module._compile (internal/modules/cjs/loader.js:1151:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1171:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```

While trying this and that, I discovered the same error if there is a missing definition for a spread target:
```
import React from 'react'

render = ->
  <div>
    <span {foo...}>test</span>
  </div>
```

**Comment by eugenet8k** [comment]
The obvious workaround would be something like:

```
import React from 'react'

export default class ReactView
  props: label: 'test'

  render: ->
    {props} = @
    <div>
      <span {props...}>test</span>
    </div>
```

This is FYI. Thanks for great work anyways, it already helps find so many unnoticed CoffeeScript code base entropy.

**Comment by helixbass** [comment]
Ok this was a missing guard (yup you are correct it was in the case that it couldn't find a definition for a spread target) in the `no-danger-with-children` rule

I can release a new version of the plugin soon, but in the meantime you could use a Github dependency:
```
yarn add --dev github:helixbass/eslint-plugin-coffee#eslint-plugin-coffee-v0.1.13-dev.1-gitpkg
```
