### ISSUE TITLE
Missing read-pkg-up dependency

### ISSUE THREAD

**Issue by edemaine** [helixbass/eslint-plugin-coffee#76]
`src/rules/no-unused-modules.coffee` depends on `read-pkg-up`:

https://github.com/helixbass/eslint-plugin-coffee/blob/a4c14d9b3461ae690600a0bfbc453e5bea7a5595/src/rules/no-unused-modules.coffee#L12

But there's no dependency in [package.json](https://github.com/helixbass/eslint-plugin-coffee/blob/master/package.json).

<details>
<summary>Full error log</summary>

```
> eslint --ext .coffee .


Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load plugin 'coffee' declared in '.eslintrc.yml': Cannot find m
odule 'read-pkg-up'
Require stack:
- C:\...\node_modules\eslint-plugin-coffee\lib\rules\no-unused-modules.js
- C:\...\node_modules\eslint-plugin-coffee\lib\index.js
- C:\...\node_modules\@eslint\eslintrc\lib\config-array-factory.js
- C:\...\node_modules\@eslint\eslintrc\lib\index.js
- C:\...\node_modules\eslint\lib\cli-engine\cli-engine.js
- C:\...\node_modules\eslint\lib\eslint\eslint.js
- C:\...\node_modules\eslint\lib\eslint\index.js
- C:\...\node_modules\eslint\lib\cli.js
- C:\...\node_modules\eslint\bin\eslint.js
Referenced from: C:\...\.eslintrc.yml
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\...\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at Object.<anonymous> (C:\...\node_modules\eslint-plugin-coffee\lib\rules\no-unused-modules.js:42:15)
    at Object.<anonymous> (C:\...\node_modules\eslint-plugin-coffee\lib\rules\no-unused-modules.js:873:4)
    at Module._compile (C:\...\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\...\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at C:\...\node_modules\eslint-plugin-coffee\lib\index.js:357:17
    at C:\...\node_modules\eslint-plugin-coffee\node_modules\lodash\lodash.min.js:41:8
    at C:\...\node_modules\eslint-plugin-coffee\node_modules\lodash\lodash.min.js:54:66
    at ue (C:\...\node_modules\eslint-plugin-coffee\node_modules\lodash\lodash.min.js:35:327)
    at C:\...\node_modules\eslint-plugin-coffee\node_modules\lodash\lodash.min.js:53:392
    at Pe (C:\...\node_modules\eslint-plugin-coffee\node_modules\lodash\lodash.min.js:40:492)
    at yf (C:\...\node_modules\eslint-plugin-coffee\node_modules\lodash\lodash.min.js:85:83)
    at l (C:\...\node_modules\eslint-plugin-coffee\node_modules\lodash\lodash.min.js:58:213)
    at C:\...\node_modules\eslint-plugin-coffee\node_modules\lodash\lodash.min.js:57:276
    at Object.<anonymous> (C:\...\node_modules\eslint-plugin-coffee\lib\index.js:360:17)
    at Object.<anonymous> (C:\...\node_modules\eslint-plugin-coffee\lib\index.js:1465:4)
    at Module._compile (C:\...\node_modules\v8-compile-cache\v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (C:\...\node_modules\v8-compile-cache\v8-compile-cache.js:159:20)
    at ConfigArrayFactory._loadPlugin (C:\...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:1036:42)
    at ConfigArrayFactory._loadExtendedPluginConfig (C:\...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:837:29)
    at ConfigArrayFactory._loadExtends (C:\...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:779:29)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (C:\...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:720:25)
    at _normalizeObjectConfigDataBody.next (<anonymous>:null:null)
    at ConfigArrayFactory._normalizeObjectConfigData (C:\...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>:null:null)
    at ConfigArrayFactory.loadInDirectory (C:\...\node_modules\@eslint\eslintrc\lib\config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (C:\...\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:379:46)
    at CascadingConfigArrayFactory.getConfigArrayForFile (C:\...\node_modules\@eslint\eslintrc\lib\cascading-config-array-factory.js:300:18)
    at FileEnumerator._iterateFilesRecursive (C:\...\node_modules\eslint\lib\cli-engine\file-enumerator.js:481:49)
    at _iterateFilesRecursive.next (<anonymous>:null:null)
    at FileEnumerator.iterateFiles (C:\...\node_modules\eslint\lib\cli-engine\file-enumerator.js:296:49)
    at iterateFiles.next (<anonymous>:null:null)
    at CLIEngine.executeOnFiles (C:\...\node_modules\eslint\lib\cli-engine\cli-engine.js:771:48)
    at ESLint.lintFiles (C:\...\node_modules\eslint\lib\eslint\eslint.js:563:23)
    at Object.execute (C:\...\node_modules\eslint\lib\cli.js:301:36)
    at main (C:\...\node_modules\eslint\bin\eslint.js:132:52)
    at Object.<anonymous> (C:\...\node_modules\eslint\bin\eslint.js:136:2)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:79:12)
    at node:internal/main/run_main_module:17:47
```

</details>

I'm using `eslint-plugin-coffee@0.1.15`.  This is weird &mdash; I thought this version was working for me &mdash; but I guess I must have tested installing but not actual linting.

**Comment by aminya** [comment]
@helixbass does not watch the repository. So tagging might help

**Comment by helixbass** [comment]
Ok this looks like another instance (per #51/#65) of a dependency "sliding out from under us", I guess `eslint-plugin-import` stopped having `read-pkg-up` as a required dependency in a more recent version so on a fresh install of `eslint-plugin-coffee` it wouldn't have gotten transitively installed

So (in #79) I pinned the version of `eslint-plugin-import` + added an explicit (pinned) dependency on `read-pkg-up`

So this should be fixed, you should be able to use the newest dev version:
```
npm install --save-dev github:helixbass/eslint-plugin-coffee#eslint-plugin-coffee-v0.1.16-dev.4-gitpkg
```

> @helixbass does not watch the repository. So tagging might help

It's not accurate that I don't watch the repository, I just haven't been getting to stuff very quickly. But so ya tagging/bugging me is a reasonable strategy for getting me to look at stuff 👍

**Comment by edemaine** [comment]
Works for me now &mdash; many thanks!

**Comment by edemaine** [comment]
A side effect of #79 is that, if I install a newer version of `eslint-plugin-import` as a peer dependency, it won't get augmented to recognize `.coffee` extensions, so I get lots of unresolved imports. I guess this is to be expected, and I'm not sure which is best... but I think I'd prefer keeping the explicit `read-pkg-up` dependency (as it's used in `eslint-plugin-coffee`) and maybe reloosening `eslint-plugin-import` dependency? Eh, it's a messy situation, given that `eslint-plugin-coffee` may depend on some implementation details of `eslint-plugin-import`.

**Comment by greghuc** [comment]
FYI I ran into the read-pkg-up issue for eslint-plugin-coffee, without knowing about this comms chain.  Pinning "eslint-plugin-import" alone to "2.24.2" worked for me.
